"""add_dependencies_and_generated_docs

Revision ID: 051b2df8478e
Revises: 454e27362b68
Create Date: 2026-08-10 18:44:20.096654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '051b2df8478e'
down_revision: Union[str, Sequence[str], None] = '454e27362b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('source_symbol_id', sa.UUID(), nullable=True),
    sa.Column('source_file_id', sa.UUID(), nullable=True),
    sa.Column('target_symbol_id', sa.UUID(), nullable=True),
    sa.Column('target_file_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_symbol_id'], ['code_symbols.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_symbol_id'], ['code_symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_docs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('symbol_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['code_symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_code_embeddings_embedding', 'code_embeddings', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_code_embeddings_embedding', table_name='code_embeddings', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('generated_docs')
    op.drop_table('dependencies')
    # ### end Alembic commands ###
